#!/bin/sh
# Systemcode laden, keine Module aus Benutzerordnern oder PYTHONPATH ausführen.
exec /usr/bin/python3 -I -B -c 'import sys,runpy; sys.path.insert(0,"/usr/share/ipsnoop"); runpy.run_module("ipsnoop",run_name="__main__")' "$@"
